In [32]:
import pandas as pd

In [33]:
df = pd.read_csv('../Raw_Data/OECD_FAO_data/HIGH_AGLINK_2020_22052021164251928.csv')
df

,LOCATION,Country,COMMODITY,Commodity,VARIABLE,Variable,TIME,Time,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,OECD,OECD countries,WT,Wheat,QP,Production,2010,2010,TONNE,Tonnes,3,Thousands,NaN,NaN,2.749563e+05,NaN,NaN
1,OECD,OECD countries,WT,Wheat,QP,Production,2011,2011,TONNE,Tonnes,3,Thousands,NaN,NaN,2.782198e+05,NaN,NaN
2,OECD,OECD countries,WT,Wheat,QP,Production,2012,2012,TONNE,Tonnes,3,Thousands,NaN,NaN,2.729270e+05,NaN,NaN
3,OECD,OECD countries,WT,Wheat,QP,Production,2013,2013,TONNE,Tonnes,3,Thousands,NaN,NaN,2.941950e+05,NaN,NaN
4,OECD,OECD countries,WT,Wheat,QP,Production,2014,2014,TONNE,Tonnes,3,Thousands,NaN,NaN,2.922292e+05,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107024,WLD,WORLD,MOL,Molasses,PC,Human consumption per capita,2025,2025,KG_HAB,Kilograms per capita,0,Units,NaN,NaN,1.226903e-08,NaN,NaN
107025,WLD,WORLD,MOL,Molasses,PC,Human consumption per capita,2026,2026,KG_HAB,Kilograms per capita,0,Units,NaN,NaN,1.215825e-08,NaN,NaN
107026,WLD,WORLD,MOL,Molasses,PC,Human consumption per capita,2027,2027,KG_HAB,Kilograms per capita,0,Units,NaN,NaN,1.205092e-08,NaN,NaN
107027,WLD,WORLD,MOL,Molasses,PC,Human consumption per capita,2028,2028,KG_HAB,Kilograms per capita,0,Units,NaN,NaN,1.194684e-08,NaN,NaN
107028,WLD,WORLD,MOL,Molasses,PC,Human consumption per capita,2029,2029,KG_HAB,Kilograms per capita,0,Units,NaN,NaN,1.184582e-08,NaN,NaN

In [34]:
df['Commodity'].unique()

array(['Wheat', 'Maize', 'Other coarse grains', 'Rice',
       "Distiller's dry grains", 'Soybean', 'Other oilseeds',
       'Protein meals', 'Vegetable oils', 'Molasses', 'Sugar',
       'Raw sugar', 'White sugar', 'High fructose corn syrup',
       'Sugar beet', 'Sugar cane', 'Beef and veal', 'Pigmeat',
       'Poultry meat', 'Sheepmeat', 'Milk', 'Fresh dairy products',
       'Butter', 'Cheese', 'Skim milk powder', 'Whole milk powder',
       'Whey powder', 'Casein', 'Ethanol', 'Biodiesel', 'Fish',
       'Fish from capture', 'Fish from aquaculture', 'Fish meal',
       'Fish oil', 'COTTON', 'ROOTS AND TUBERS', 'PULSES', 'Fertilizer',
       'Oil'], dtype=object)

In [35]:
df['Country'].unique()

array(['OECD countries', 'Turkey', 'United States', 'NORTH AMERICA',
       'EUROPE', 'Russian Federation', 'Ukraine', 'AFRICA',
       'South Africa', 'LATIN AMERICA', 'Paraguay', 'ASIA',
       'Saudi Arabia', 'Thailand', 'Viet Nam', 'WORLD'], dtype=object)

In [36]:
column_list = ['Fish']

In [37]:
df = df[(df['Country'].str.contains('WORLD'))  &  (df['Commodity'].isin(column_list)) & (df['Variable'].str.contains('Consumption'))]
df

,LOCATION,Country,COMMODITY,Commodity,VARIABLE,Variable,TIME,Time,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
57680,WLD,WORLD,FH,Fish,QC,Consumption,2010,2010,TONNE,Tonnes,3,Thousands,NaN,NaN,145838.22,NaN,NaN
57681,WLD,WORLD,FH,Fish,QC,Consumption,2011,2011,TONNE,Tonnes,3,Thousands,NaN,NaN,152448.90,NaN,NaN
57682,WLD,WORLD,FH,Fish,QC,Consumption,2012,2012,TONNE,Tonnes,3,Thousands,NaN,NaN,152111.47,NaN,NaN
57683,WLD,WORLD,FH,Fish,QC,Consumption,2013,2013,TONNE,Tonnes,3,Thousands,NaN,NaN,157060.80,NaN,NaN
57684,WLD,WORLD,FH,Fish,QC,Consumption,2014,2014,TONNE,Tonnes,3,Thousands,NaN,NaN,160193.34,NaN,NaN
57685,WLD,WORLD,FH,Fish,QC,Consumption,2015,2015,TONNE,Tonnes,3,Thousands,NaN,NaN,165438.63,NaN,NaN
57686,WLD,WORLD,FH,Fish,QC,Consumption,2016,2016,TONNE,Tonnes,3,Thousands,NaN,NaN,167088.78,NaN,NaN
57687,WLD,WORLD,FH,Fish,QC,Consumption,2017,2017,TONNE,Tonnes,3,Thousands,NaN,NaN,172392.57,NaN,NaN
57688,WLD,WORLD,FH,Fish,QC,Consumption,2018,2018,TONNE,Tonnes,3,Thousands,NaN,NaN,178416.68,NaN,NaN
57689,WLD,WORLD,FH,Fish,QC,Consumption,2019,2019,TONNE,Tonnes,3,Thousands,NaN,NaN,177934.84,NaN,NaN
57690,WLD,WORLD,FH,Fish,QC,Consumption,2020,2020,TONNE,Tonnes,3,Thousands,NaN,NaN,180496.72,NaN,NaN
57691,WLD,WORLD,FH,Fish,QC,Consumption,2021,2021,TONNE,Tonnes,3,Thousands,NaN,NaN,179717.42,NaN,NaN
57692,WLD,WORLD,FH,Fish,QC,Consumption,2022,2022,TONNE,Tonnes,3,Thousands,NaN,NaN,183479.64,NaN,NaN
57693,WLD,WORLD,FH,Fish,QC,Consumption,2023,2023,TONNE,Tonnes,3,Thousands,NaN,NaN,186463.06,NaN,NaN
57694,WLD,WORLD,FH,Fish,QC,Consumption,2024,2024,TONNE,Tonnes,3,Thousands,NaN,NaN,189007.62,NaN,NaN
57695,WLD,WORLD,FH,Fish,QC,Consumption,2025,2025,TONNE,Tonnes,3,Thousands,NaN,NaN,191307.96,NaN,NaN
57696,WLD,WORLD,FH,Fish,QC,Consumption,2026,2026,TONNE,Tonnes,3,Thousands,NaN,NaN,192110.82,NaN,NaN
57697,WLD,WORLD,FH,Fish,QC,Consumption,2027,2027,TONNE,Tonnes,3,Thousands,NaN,NaN,195893.06,NaN,NaN
57698,WLD,WORLD,FH,Fish,QC,Consumption,2028,2028,TONNE,Tonnes,3,Thousands,NaN,NaN,198256.61,NaN,NaN
57699,WLD,WORLD,FH,Fish,QC,Consumption,2029,2029,TONNE,Tonnes,3,Thousands,NaN,NaN,200545.10,NaN,NaN

In [38]:
df.to_csv('../Preprocessed_data/Flourish_data/total_world_fish_consumption.csv')